<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.
/**
 * An Element Library to help theme development.
 *
 * This code has been taken and slightly adapted from :
 * https://github.com/totara/moodle/tree/mdl-feature-element-library
 * and https://tracker.moodle.org/browse/MDL-36558 but never landed in moodle core.
 * This is still work in progress.  The original copyright seems to be from
 * Simon Coggins, but has been authored by various developpers from Totara.
 *
 * @package   theme_clboost
 * @copyright Simon Coggins
 * @license   http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

define('LOREMIPSUM', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu accumsan nulla.' .
    ' Cras elementum tincidunt dictum. Phasellus varius, est non ornare mattis, leo velit congue libero, vitae suscipit ipsum urna'
    .
    ' sed orci. Pellentesque venenatis pulvinar lobortis. Vestibulum iaculis commodo eros quis volutpat. Morbi vitae dapibus ante.'
    . 'Nullam convallis interdum ipsum, venenatis consequat eros faucibus sed. Pellentesque non tellus vel eros ullamcorper' .
    'sollicitudin ut in lectus. Sed aliquet gravida porta.');

/**
 * Returns the HTML source generated by executing the file provided
 *
 * @param string $filename Name of the file to display
 * @return string source code produced by the code in $filename
 */
function get_source_output($filename) {
    // We don't know what globals the file might need.
    global $OUTPUT, $USER, $SESSION, $DB, $CFG;
    if (!file_exists($filename)) {
        return false;
    }
    ob_start();
    include($filename);
    return htmlentities(ob_get_clean());
}

/**
 * Returns the code contained within the file provided, escaped so
 * as to be suitable for printing to an HTML page
 *
 * @param string $filename Name of the file
 * @return string copy of the code in $filename
 */
function get_html_output($filename) {
    if (!file_exists($filename)) {
        return false;
    }
    return htmlentities(file_get_contents($filename));
}


