<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.
/**
 * An Element Library to help theme development.
 *
 * This code has been taken and slightly adapted from :
 * https://github.com/totara/moodle/tree/mdl-feature-element-library
 * and https://tracker.moodle.org/browse/MDL-36558 but never landed in moodle core.
 * This is still work in progress.  The original copyright seems to be from
 * Simon Coggins, but has been authored by various developpers from Totara.
 *
 * @package   theme_clboost
 * @copyright Simon Coggins
 * @license   http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */
require_once(dirname(__FILE__) . '../../../../../config.php');
global $CFG, $PAGE, $OUTPUT;
require_once($CFG->libdir . '/adminlib.php');

$strheading = 'Element Library: Notifications';
$url = new moodle_url('/theme/clboost/tools/elementlibrary/notifications.php');

// Start setting up the page.
$params = array();
$PAGE->set_context(context_system::instance());
$PAGE->set_url($url);
$PAGE->set_title($strheading);
$PAGE->set_heading($strheading);

admin_externalpage_setup('clboostelementlibrary');

echo $OUTPUT->header();

echo html_writer::link(new moodle_url('/theme/clboost/tools/elementlibrary/'), '&laquo; Back to index');
echo $OUTPUT->heading($strheading);

echo $OUTPUT->notification('This is an error notification <a href="#">with a link</a>');

echo $OUTPUT->notification('This is a success notification <a href="#">with a link</a>', 'notifysuccess');

echo $OUTPUT->notification('This is a standard notification <a href="#">with a link</a>', 'notifymessage');

echo $OUTPUT->notification('This is a redirect message notification. It looks like it\'s supposed to be used' .
    ' on a blank page as it has 10% top margin', 'redirectmessage');

echo $OUTPUT->error_text('This is an error generated using error_text(). I think this is used in form validation errors.');

echo $OUTPUT->box('This is a notice box <a href="#">with a link</a>, generated via box() with "generalbox" and "notice"' .
    ' classes added. Used by moodle in various places.', array('generalbox', 'notice'));

echo $OUTPUT->confirm('This is a confirmation box <a href="#">with a link</a>, generated by confirm(). It has the "box"' .
    'and "generalbox" styles applied, as well as an id of "notice"', new moodle_url('notifications.php'),
    new moodle_url('notifications.php'));

echo $OUTPUT->footer();
